name: continous-deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DOCKERHUB_TOKEN
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: yashsh13/courseapp:${{ github.sha }}

      - name: Deploying to a Virtual Machine
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.VM_IP }} -t "docker stop courseapp && docker rm $(sudo docker ps -a -q) && docker run --name courseapp -e MONGODB_URL=${{ secrets.MONGODB_URL }} -p 3000:3000 -d yashsh13/courseapp:${{ github.sha }}"